name: "my-gh-action"
run-name: "${{ github.actor }} is running a pipeline"
on: 
      push: 
            branches: [ "main" ]
permissions:
      id-token: write
      contents: read
jobs:
      install-dotnet-CLI:
          runs-on: ubuntu-latest
          steps:
          - name: .NET Core CLI
            uses: baruchiro/github-actions@cfa460ee18f07031ba85ff00d2184fabf03f9f1f
          - name: Check Dotnet version
            run: dotnet --info
            
        
          
      
