name: "my-gh-action"
run-name: "${{ github.actor }} is running a pipeline"
on: 
      push: 
            branches: [ "main" ]
      
permissions:
      id-token: write
      contents: read
jobs:
      docker-login:
            runs-on: ubuntu-latest
            steps:
                  - name: Azure Login
                    uses: Azure/login@v2.1.0
                    with:
                        client-id: b2a47d1d-3039-4e62-883a-35e3c288ac66
                        tenant-id: 5bb0c9b3-b167-4d84-8694-ea7e8aa516e8
                        subscription-id: b2a47d1d-3039-4e62-883a-35e3c288ac66
                        environment: azurecloud
                        auth-type: SERVICE_PRINCIPAL


                   
                  

                  
                  
        
          
      
