name: "my-gh-action"
run-name: "{{ git.actor }} is running a pipeline"
on: [push]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/webapps-deploy@v2.2.12
        with:
          # Name of the Azure Web App
          app-name: my-html-app
          package: ${{ github.workspace }}
          
