name: "my-gh-action"
run-name: "${{ github.actor }} is running a pipeline"
on: [push]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@v2.1.0
        with: 
          creds: ${{ env.AZURE_CRED }}
          enable-AzPSSession: true
      - uses: Azure/webapps-deploy@v2.2.12
        with:
          app-name: my-html-app
          package: ${{ env.workspace }}
          
