name: "my-gh-action"
run-name: "${{ github.actor }} is running a pipeline"
on: 
      push: 
            branches: [ "main" ]
permissions:
      id-token: write
      contents: read
jobs:
      azure-CLI-setup:
            runs-on: ubuntu-latest 
            steps:
            - name: Azure CLI Action
              uses: Azure/cli@v2.0.0
            - name: start-with-az
              run: az --help
                  
        
          
      
