name: "my-gh-action"
run-name: "${{ github.actor }} is running a pipeline"
on: [push]

permissions:
      id-token: write
      contents: read

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@hf_447_release
        with: 
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          enable-AzPSSession: true
          allow-no-subscriptions: true
      - uses: Azure/webapps-deploy@v2.2.12
        with:
          app-name: my-html-app
          package: ${{ secrets.workspace }}
          resource-group-name: webapp-resource-group
          target-path: /
          
