name: "my-gh-action"
run-name: "${{ github.actor }} is running a pipeline"
on: [push]

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@v2.1.0
        with: 
          subscription-id: b2a47d1d-3039-4e62-883a-35e3c288ac66
          tenant-id: 5bb0c9b3-b167-4d84-8694-ea7e8aa516e8
          client-id: 646803a9-84fb-4fc7-b77a-8070e4fcc3a9
      - uses: Azure/webapps-deploy@v2.2.12
        with:
          app-name: my-html-app
          package: ${{ github.workspace }}
          
